import { GoogleGenAI, Type } from '@google/genai';
import { StorySetup, StoryBeat, StoryConfig } from '../types';

// Initialize SDK securely using environment variable
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY, vertexai: true });

export const brainstormStory = async (prompt: string): Promise<StorySetup> => {
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: `Brainstorm a comic book setup based on this idea: "${prompt}"`,
    config: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          premise: { type: Type.STRING, description: "A 30-word exciting premise." },
          heroDesc: { type: Type.STRING, description: "Vivid visual description of the hero." },
          friendDesc: { type: Type.STRING, description: "Vivid visual description of the co-star/friend." },
          villainDesc: { type: Type.STRING, description: "Vivid visual description of the villain." },
          recommendedGenre: { 
            type: Type.STRING, 
            description: "Must be one of: Classic Horror, Superhero Action, Dark Sci-Fi, High Fantasy, Neon Noir Detective, Wasteland Apocalypse, Lighthearted Comedy, Teen Drama / Slice of Life" 
          }
        },
        required: ["premise", "heroDesc", "friendDesc", "villainDesc", "recommendedGenre"]
      }
    }
  });

  if (!response.text) throw new Error("Failed to generate brainstorm.");
  return JSON.parse(response.text) as StorySetup;
};

const generateSvgFallback = async (prompt: string): Promise<string> => {
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: `Create a bold, retro comic book style SVG illustration of: ${prompt}. 
    Use thick black outlines, vibrant flat colors (red, yellow, blue), and dynamic composition.
    Return ONLY valid SVG XML code. Do not wrap in markdown blocks like \`\`\`svg. Just the raw <svg> tag and its contents.
    Ensure it has a viewBox="0 0 800 600" and xmlns="http://www.w3.org/2000/svg".`,
  });
  
  let svgStr = response.text || '';
  // Clean up potential markdown if the model ignored instructions
  svgStr = svgStr.replace(/```xml\n?/g, '').replace(/```svg\n?/g, '').replace(/```\n?/g, '').trim();
  
  if (!svgStr.startsWith('<svg')) {
     // Ultimate fallback if it completely fails to return SVG
     svgStr = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 600"><rect width="100%" height="100%" fill="#facc15"/><text x="50%" y="50%" font-family="sans-serif" font-size="40" font-weight="bold" text-anchor="middle" fill="#000">IMAGE GENERATION FAILED</text><text x="50%" y="60%" font-family="sans-serif" font-size="20" text-anchor="middle" fill="#000">${prompt.substring(0, 50)}...</text></svg>`;
  }

  const base64Svg = btoa(unescape(encodeURIComponent(svgStr)));
  return `data:image/svg+xml;base64,${base64Svg}`;
};

export const generateImage = async (prompt: string): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: `Retro comic book art style, bold ink lines, vibrant colors, halftone patterns. ${prompt}`,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: '4:3',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/jpeg;base64,${base64ImageBytes}`;
    }
    throw new Error("No image generated by Imagen.");
  } catch (error) {
    console.warn("Imagen generation failed, falling back to SVG:", error);
    return await generateSvgFallback(prompt);
  }
};

export const generateBeat = async (
  config: StoryConfig, 
  history: StoryBeat[], 
  chosenAction?: string
): Promise<StoryBeat> => {
  
  let historyContext = history.map((b, i) => `Panel ${i+1}: ${b.caption} | ${b.dialogue}`).join('\n');
  let prompt = `
    You are writing a retro comic book.
    Genre: ${config.setup.recommendedGenre}
    Language: ${config.language}
    Tone: ${config.tone}
    Premise: ${config.setup.premise}
    
    Previous Panels:
    ${historyContext || "None. This is the opening panel."}
    
    ${chosenAction ? `The reader chose: "${chosenAction}". Continue the story based on this.` : "Start the story with an exciting opening hook."}
    
    Generate the next panel's details.
  `;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: prompt,
    config: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          caption: { type: Type.STRING, description: "Narrator caption box text." },
          dialogue: { type: Type.STRING, description: "Character speech bubble text. Keep it punchy." },
          scene: { type: Type.STRING, description: "Highly detailed visual description of the panel for the illustrator." },
          focus_char: { type: Type.STRING, description: "Which character is the main focus? (hero, friend, villain, or none)" },
          choices: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Provide exactly 3 distinct, action-oriented choices for what happens next."
          }
        },
        required: ["caption", "dialogue", "scene", "focus_char", "choices"]
      }
    }
  });

  if (!response.text) throw new Error("Failed to generate story beat.");
  const beatData = JSON.parse(response.text);
  
  return {
    id: crypto.randomUUID(),
    ...beatData
  };
};
